/vis/open OGL 600x600-0+0
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose 0
#
# Draw geometry and set the perspective
/vis/drawVolume
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 90. 0.
/vis/viewer/zoom 1.4
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 20 um
#
# Draw smooth trajectories at end of event, showing trajectory points
/vis/scene/add/trajectories smooth
#
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
#
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/list

#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add alpha
#/vis/filtering/trajectories/particleFilter-0/invert true

/vis/modeling/trajectories/drawByParticleID-0/set n pink
#
/vis/scene/endOfEventAction accumulate
/vis/scene/add/hits
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose 0
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush